Fix obus derivation
type_conv is not required, nor it is provided anymore:

error: Function called without required argument "type_conv" at /home/joris/dividat/playos/pkgs/ocaml-modules/obus/default.nix:3
(use '--show-trace' to show detailed location information)