Remove minimal profile imports
Importing minimal profiles, there is an error building `gtk3`:

```
ERROR: Dependency "cairo-xlib" not found
```

The same problem is discussed in this issue:
https://github.com/NixOS/nixpkgs/issues/102137

The problem is coming from the import the minimal profile, setting
noXlibs, along with others settings:

```nix
environment.noXlibs = mkDefault true;
i18n.supportedLocales = [ (config.i18n.defaultLocale + "/UTF-8") ];
documentation.enable = mkDefault false;
documentation.nixos.enable = mkDefault false;
```

What is the impact on `playos-installer.iso` size ?

- develop: 1.15 G
- develop without minimal: 1.22 G
- nixpgks-20.09 without minimal: 1.29 G
- nixpkgs-20.09 without minimal but without documentation: 1.26 G

There is an impact, but it’s not enorm.

However, we can further inquire whether gtk is required for a non
graphical ISO.