Switch to replaceVars and force path interpolation
nixpkgs 25.11 deprecates substituteAll, however replaceVars has slightly
different behaviour.  Using `substituteAll`, the substitute values were
implicitly coerced to store paths. `replaceVars` doesn't do that and it
causes local paths to appear (at least) in tests, e.g. in e2e-tests:

  Traceback (most recent call last):
    File "/nix/store/qkjvh813d6kjw4clp5kh2fgp3gkb2l8y-install-playos-2026.3.0-TEST/bin/.install-playos-wrapped", line 497, in
  <module>
      _main(parser.parse_args())
    File "/nix/store/qkjvh813d6kjw4clp5kh2fgp3gkb2l8y-install-playos-2026.3.0-TEST/bin/.install-playos-wrapped", line 438, in
  _main
      install_bootloader(disk, machine_id)
    File "/nix/store/qkjvh813d6kjw4clp5kh2fgp3gkb2l8y-install-playos-2026.3.0-TEST/bin/.install-playos-wrapped", line 215, in
  install_bootloader
      shutil.copy2(GRUB_CFG, '/mnt/boot/grub/grub.cfg')
    File "/nix/store/kjgslpdqchx1sm7a5h9xibi5rrqcqfnl-python3-3.12.8/lib/python3.12/shutil.py", line 475, in copy2
      copyfile(src, dst, follow_symlinks=follow_symlinks)
    File "/nix/store/kjgslpdqchx1sm7a5h9xibi5rrqcqfnl-python3-3.12.8/lib/python3.12/shutil.py", line 260, in copyfile
      with open(src, 'rb') as fsrc:
           ^^^^^^^^^^^^^^^
  FileNotFoundError: [Errno 2] No such file or directory: '/home/yfyf/src/playos2/skeleton/bootloader/grub.cfg'